### PR TITLE
Enhance file section when file name is too big

### LINKED ISSUE #56: [ENHANCEMENT]- Enhance navigation on Files section when file name is too big
### Description

Currently the Files section actives the horizontal scrolling when a file name is too big

image

### Reproduction URL

https://storz.pages.dev/app/myFiles

### Reproduction steps

```bash
1. Go to the Storz app https://storz.pages.dev/
2. Login
3. Add a new file with a large name
4. See behavior
```

### Screenshots

```bash
![image](https://user-images.githubusercontent.com/48018975/193726016-74c69263-7c1f-4f13-8045-83a1b36d005f.png)
```

### Logs

_No response_

### Browsers

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by nujovich**
# Description

The application now will have an enhanced user experience while navigating through Files Section when the file name is too large

Mobile:

image

image

Desktop:

image

image

Even when the file name is not that large, for mobile devices the Ellipsis truncation is done for better visualization:

image

Fixes #56 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by anomic30** [comment]
Hi @nujovich, as you can see these are not aligned:
image

**Comment by nujovich** [comment]
> Hi @nujovich, as you can see these are not aligned:
> image

Oops ! Nice catch. Let me work on that.

**Comment by anomic30** [comment]
Hi @nujovich, is it fixed now?

**Comment by nujovich** [comment]
Hi @anomic30! I haven't had the chance to look at it. I will upload the fix shortly. Will let you know as soon as the commit is made

**Comment by nujovich** [comment]
Now's looking better @anomic30 !

image

**Review by anomic30 — APPROVED** [review]
LGTM!

**Pull request merged**
