### PR TITLE
Fix: Issue-104 Files with same name

### LINKED ISSUE #104: 🐛 [BUG] - 2 files with same name
### Description

when uploading files, if you are uploading a file (same one or an other one) with the same name, it'll be stored. 
The user must be advertised and specify his intention

### Reproduction URL

https://github.com/ThomasSed/Storz

### Reproduction steps

```bash
1. Go to "home"
2. Click on "upload"
3. upload a file
4. do the 3 first steps a second time, with the same file (for example) 
5. go to your repository, you must see 2 files with same name
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

_No response_

### Browsers

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by mani-rsg**
# Description
If an existing file is uploaded again, a confirmation modal will pop up saying _"A file with name x already exists. Do you want to override it?_. If Yes, then the existing file will be overridden, and on No, the duplicate file will be skipped and the rest of the files will be uploaded. 

This will work even when trying to upload multiple duplicate files along with new files.

Fixes #104

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Screenshot: 
image

### CODE REVIEW

**Comment by mani-rsg** [comment]
Hi @anomic30, I haven't modified the delete operation using the unique _id as this will not be required, the current code will not allow any files to be uploaded with the same name.  Let me know if this change is needed as well, I will raise it as a separate PR addressing issue #105. Let me know your thoughts.

**Review by anomic30 — APPROVED** [review]
Awesome!

**Comment by ThomasSed** [comment]
> Hi @anomic30, I haven't modified the delete operation using the unique _id as this will not be required, the current code will not allow any files to be uploaded with the same name. Let me know if this change is needed as well, I will raise it as a separate PR addressing issue #105. Let me know your thoughts.

as #105 is a cid problem and not a name problem, it won't resolve.
if two files with different names have equals contents (for any reason) cids will be sames.
You can fix this too if you want (I gave a part of the solution), I don't have the time rn and october is running, gl

**Comment by mani-rsg** [comment]
Hi @ThomasSed, thanks for your suggestion fixed issue #105 as well

**Pull request merged**
