### PR TITLE
Pagignation added for my files page

### LINKED ISSUE #2: Add pagination in My Files page
Add pagination in the table view of the My Files page.

### PR DESCRIPTION
**Pull request by detronetdip**
I have added pagination system in My Files page.

Fixes #2 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by detronetdip** [comment]
@anomic30  please review it.

**Comment by anomic30** [comment]
@Sneakad, check the UI. It looks like this:

image

**Comment by Sneakad** [comment]
@detronetdip can you put the numbers in boxes? For example, if the user is on the second page then the selected box bg will be solid other boxed will only have border-radius.
image

**Comment by detronetdip** [comment]
Sure why not

**Comment by anomic30** [comment]
@detronetdip, show us the ss here.

**Comment by detronetdip** [comment]
@anomic30  as it is showing conflicts with base branch should I resolve it by merging the base base branch?

**Comment by anomic30** [comment]
Hi, @detronetdip, each page should show at least 8 files.
Pull the latest changes from the main branch, resolve conflicts.

**Comment by detronetdip** [comment]
@anomic30  done

**Review by anomic30 — APPROVED** [review]
LGTM!

**Review by Sneakad — APPROVED** [review]

**Pull request merged**
