### PR TITLE
Added filtering and sorting feature for files

### LINKED ISSUE #3: Add a sorting feature
Add a sorting feature to the My Files page.

For example: 

- Sort by Upload date ( ascending or descending )
- Sort by File names ( alphabetically )
- Sort by File size ( smaller or larger )

### LINKED ISSUE #4: Add a filtering feature
Add a filtering feature to the My Files page.

For example :
- Filter by File types ( .pdf/.png/.jpeg etc )
- Filter by File status ( public/private )

### PR DESCRIPTION
**Pull request by ozair-dev**
# Description

Added filtering and sorting features for the files. Changes had to be made to both frontend and the backend. Previously 
(already available) **search filter** was implemented on the frontend not the backend. So it was inefficient because all files had to be fetched and then filtered according to the searched text on frontend. 
Now all sorting and filtering is done on the backend and and filtered files sent to client.

This is what implementation looks like

Screenshot from 2022-10-09 19-07-57
Screenshot from 2022-10-09 22-54-20
Screenshot from 2022-10-09 19-09-51

I made changes to only about 5 files but after merging the upstream/main into my branch, it is now showing 17 files changed. Does this make it difficult for you to review the changes. 
Please review and let me know if you want more change

Fixes #3 
Fixes #4 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ozair-dev** [comment]
Hey @anomic30 please review my changes and let me know if they are good enough to be merged? I'll then resolve the conflicts.

**Comment by anomic30** [comment]
Hi @ozair-dev, can you please resolve the conflicts and raise a PR again?

**Comment by ozair-dev** [comment]
@anomic30 do I really have to raise another PR? Can't I just commit to this already made PR?

**Comment by anomic30** [comment]
@ozair-dev
Yes, I am closing this PR as of now.

**Pull request closed without merging**
